version: '3'
services:
  terraform:
    container_name: 'terraform'
    build:
      context: ./
      dockerfile: ./dockerfile/terraform/Dockerfile
    tty: true
    volumes:
      - ./:/terraform
    