version: '3'
services:
  terraform:
    container_name: 'terraform'
    build:
      context: ./
      dockerfile: ./dockerfile/terraform/Dockerfile
    volumes:
      - ./terraform:/terraform
    env_file:
      - ./dockerfile/terraform/.env